export { Login } from './LoginScreen'
export { SingUpCpfScreen } from './SingUpCpfScreen'
export { SingUpNameScreen } from './SingUpNameScreen'
export { SingUpPasswordScreen } from './SingUpPasswordScreen'
export { SingUpPhoneScreen } from './SingUpPhoneScreen'
